{{- range $f := .Values.functions }}
apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "func-%s" $f.name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 $f.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ $fullname }}
        image: "alinflorinciu/dynamic-faas:latest"
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        ports:
        - containerPort: {{ default 3000 $f.port | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ default 3000 $f.port | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ default 3000 $f.port | int }}
        resources:
{{ toYaml $f.resources | indent 10 }}
{{- end }}