{{- range $f := .Values.functions }}
apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "func-%s" $f.name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 $f.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
      {{- if or $.Values.functionPodsAnnotations }}
      annotations:
      {{- with $.Values.functionPodsAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
      volumes:
      - name: pv-app
        persistentVolumeClaim:
          claimName: pvc-dynamic-faas
          readOnly: true
      containers:
      - name: {{ $fullname }}
        image: "alinflorinciu/dynamic-faas:latest"
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        volumeMounts:
        - mountPath: "/app"
          name: pv-app
          subPath: {{ $f.name }}
          readOnly: true
        ports:
        - containerPort: {{ default 3000 $f.port | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ default 3000 $f.port | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ default 3000 $f.port | int }}
        resources:
{{ toYaml $f.resources | indent 10 }}
{{- end }}