apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic-faas-data
  labels:
    app: {{ .Chart.Name }}
spec:
  {{ if .Values.dataStorage.storageClassName }}
  storageClassName: {{ .Values.dataStorage.storageClassName }}
  {{ end }}
  accessModes:
    - {{ .Values.dataStorage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.dataStorage.size }}