apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic-faas
  labels:
    app: {{ .Chart.Name }}
spec:
  {{ if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{ end }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}